# Generated by Django 4.2.1 on 2023-06-24 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_idusuario_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='noticia',
            name='ubicacion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=models.TextField(),
        ),
    ]
