# Generated by Django 4.2.1 on 2023-06-24 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_destacada_noticia_fecha_noticia_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='estado',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='noticias.estado'),
        ),
    ]
