# Generated by Django 4.2.1 on 2023-07-07 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_noticia_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noticias.estado'),
        ),
    ]
